name: 'LeetCode Today Record'

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  beancount:
    runs-on: ubuntu-latest
    steps:
    - name: Webhook
      uses: zzzze/webhook-trigger@master
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
